server:
    port: 8081

spring:
    application:
        name: cloud-demo
eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
#            defaultZone: http://192.168.50.150:${server.port}/eureka/,http://192.168.50.150:8082/eureka
            defaultZone: http://10.10.100.11:${server.port}/eureka/,http://10.10.100.11:8082/eureka
        register-with-eureka: true
        fetch-registry: true



