spring:
    application:
        name: mybatis-demo
    datasource:
        master:
            url: jdbc:mysql://192.168.1.58:3306/edb_a20000?useSSL=false
            username: root
            password: Server-wms654321
        slave:
            url: jdbc:mysql://192.168.1.58:3306/edb_b20000?useSSL=false
            username: root
            password: Server-wms654321

    redis:
        host: 192.168.50.26
        port: 6379
        password:

#mybatis:
#    config-location: classpath:mybatis-config.xml
#    type-aliases-package: com.yuanwj.mybatisdemo.model
#    configuration:
#        map-underscore-to-camel-case: true
#    mapper-locations: classpath:mapper/**/*.xml

server:
    port: 8083
eureka:
    instance:
        hostname: localhost
        metadataMap:
            instanceId: ${spring.application.name}:${random.value}
    client:
        service-url:
#            defaultZone: http://192.168.50.150:8081/eureka,http://192.168.50.150:8082/eureka
            defaultZone: http://localhost:8081/eureka,http://localhost:8082/eureka